name: incas-emotions
channels:
  - conda-forge
  - defaults
dependencies:
  - flask
  - flask-cors
  - tornado
  - requests
  - pip
  - pip:
    - charset-normalizer==2.0.12
    - click==8.1.0
    - colorama==0.4.4
    - cycler==0.11.0
    - "--editable=git+https://github.com/gchochla/ekphrasis.git@master#egg=ekphrasis"
    - filelock==3.6.0
    - fonttools==4.31.2
    - ftfy==6.1.1
    - huggingface-hub==0.4.0
    - idna==3.3
    - joblib==1.1.0
    - kiwisolver==1.4.2
    - matplotlib==3.5.1
    - nltk==3.7
    - numpy==1.22.3
    - packaging==21.3
    - pillow==9.0.1
    - pyparsing==3.0.7
    - python-dateutil==2.8.2
    - pyyaml==6.0
    - regex==2022.3.15
    - requests==2.27.1
    - sacremoses==0.0.49
    - six==1.16.0
    - termcolor==1.1.0
    - tokenizers==0.11.6
    - torch==1.11.0
    - tqdm==4.63.1
    - transformers==4.17.0
    - typing-extensions==4.1.1
    - ujson==5.1.0
    - urllib3==1.26.9
    - wcwidth==0.2.5